### ISSUE TITLE
#2 Making images available

### ISSUE THREAD

**Issue by Robert-Schurig** [Robert-Schurig/Capstone-App#1]
### Value Proposition

As a user I want to see pictures on the main page as a first step to use the app.

### Description

![Bildschirm­foto 2022-11-28 um 11 57 43](https://user-images.githubusercontent.com/114500583/204261188-9abb6110-43cd-460c-93da-524945a4113e.png)

### Acceptance Criteria

- [ ] either connect the app with an API or save image data locally
- [ ] create a function that displays random pictures from the used data source

### Tasks

(for developers team)

- [ ] create a new branch
- [ ] decide whether to use an API or to save data locally
- [ ] create a working connection do the source of data 

### Sizing/Complexity

L
