### ISSUE TITLE
#7 Remove favorites

### ISSUE THREAD

**Issue by Robert-Schurig** [Robert-Schurig/Capstone-App#13]
### Value Proposition

As a user, I need an option
to remove images from the favorites page in case I don't like one or some of them anymore

### Description

![Bildschirm­foto 2022-12-16 um 14 21 50](https://user-images.githubusercontent.com/114500583/208108084-a77429ec-2689-4b7b-8db0-6dc23ec90a51.png)

### Acceptance Criteria

- [x] If the user clicks on the X-Button the image has to disappear from the favorites page

### Tasks

(for developers team)

- [x] Add a button to the favorite element
- [x] Create a function that allows to remove the chosen image from the favorites array
- [x] Connect the button with the function

### Sizing/Complexity

M
