### ISSUE TITLE
#8 Personal Login

### ISSUE THREAD

**Issue by Robert-Schurig** [Robert-Schurig/Capstone-App#14]
### Value Proposition

As a user I need a login function 
to be able to have a personal space with my saved data.

### Description

![Bildschirm­foto 2022-12-19 um 10 23 04](https://user-images.githubusercontent.com/114500583/208391957-f7fd3c62-ebe2-4e68-8d7d-cdbeca592a4b.png)

### Acceptance Criteria

- [ ] When opening the app, a login page should appear
- [ ] On entering the data and pressing to login button, the images page should be displayed

### Tasks

(for developers team)

- [ ] Create a login page
- [ ] Move the image display to another page to have the login on the home page.
- [ ] Add functionality to make entered data accessible (onSubmit-Event)
- [ ] link the button to the image page.
- [ ] At first, it will only be a fake login without authentication

### Sizing/Complexity

 M
