### ISSUE TITLE
#10 Authenticated login

### ISSUE THREAD

**Issue by Robert-Schurig** [Robert-Schurig/Capstone-App#15]
### Value Proposition

As a user, I need to have a login with authentication
to be able to access my account that no one else can enter

### Description

<img width="360" alt="Bildschirm­foto 2022-12-19 um 11 36 32" src="https://user-images.githubusercontent.com/114500583/208407500-f0da0347-eddf-4550-8ccd-58702bb2855b.png">

### Acceptance Criteria

- [ ] The user enters his personal username and password
- [ ] Only if both are correct, he can enter the app

### Tasks

(for developers team)

- [ ] Install NextAuth
- [ ] Configure Github Apps under settings (for local development and Production Domain)
- [ ] Create `/auth/[...nextauth].js` in /api folder and configure correctly (see Documentation)
- [ ] Create .env.local and put ID and Secret in it.
- [ ] Create environment variable NEXTAUTH_SECRET and generate with command `openssl rand -base64 32`
- [ ] Integrate Login/Logout user infos in Frontend
- [ ] Protect API-Routes
- [ ] Deploy with new ID and Secret of Production App
- [ ] Set `VERCEL_ENV` on `preview` and configure test credentials to be able to test the functionality.

### Sizing/Complexity

 L

**Comment by ufelgen** [comment]
Hi Robert, size-wise I think this is a really good US. 

However, in your tasks you mention that you still need to include specifics about how to implement the authentication process, so I believe the US cannot be approved if it's not finished. 
Also, I would specify where the login page will be rendered - I guess on the main index.js page? What happens with the content that was there previously? rendered after successful login on the same page? or routing to a different page? also, how will registration be different from logging in? 

I'm looking forward to the workshop, too! :)

**Comment by Robert-Schurig** [comment]
Thanks for your comments. The question whether there will be a new page or not is answered in the previous US: There will be a new page.
I know that this is not the best way to describe the tasks but concerning authentication I have really no detailed procedure to put down. So I did it that way. I will add them tomorrow and ask for approval again.
You are right concerning the registration. I will probably take care of that first.
