### ISSUE TITLE
#9 Registration 

### ISSUE THREAD

**Issue by Robert-Schurig** [Robert-Schurig/Capstone-App#16]
### Value Proposition

As a user who uses the app for the first time, I need a registration page
to be able to enter data that will allow me to use the app.

### Description

<img width="354" alt="Bildschirm­foto 2022-12-19 um 16 21 45" src="https://user-images.githubusercontent.com/114500583/208459778-7f572102-4ab8-462f-84e1-fae289716fb5.png">

### Acceptance Criteria

- [ ] The user can enter his data like family name, first name, e-mail and a password that he has to confirm. It has to consist of 6 characters at least.
- [ ] On clicking the Register-Button, a new account is created in which his data is saved 
- [ ] Registration allows the user to log in the next time he uses the app.

### Tasks

(for developers team)

- [ ] Make use of the existing basic registration page.
- [ ] Add a link to the respective button on the login page.
- [ ] Create a database for user data.
- [ ] Write a function to load entered data into the database.
- [ ] Add an onSubmit-event to the registration form to use the entered data and to display them on the profile page.
- [ ] Add necessary attributes to the input fields to make sure that all required data are provided.

### Sizing/Complexity

L
