### ISSUE TITLE
#1 Accessing the app

### ISSUE THREAD

**Issue by Robert-Schurig** [Robert-Schurig/Capstone-App#2]
### Value Proposition

As a user interested in art I need to enter the app easily
to be able to discover new art

### Description

![Bildschirm­foto 2022-11-28 um 11 05 14](https://user-images.githubusercontent.com/114500583/204250469-9c1c6983-5131-43db-87a1-f8b3d60677be.png)

### Acceptance Criteria

- After clicking the "Sign in"-button, the profile page opens. An actual login-function maybe added later.

### Tasks

(for developers team)

- [ ] create the required pages (starting page, profile page)
- [ ] Add input fields to the starting page
- [ ] Add "Sign in"-button to the starting page
- [ ] Add options to the profile page

### Sizing/Complexity

M
