### ISSUE TITLE
#4 Like/Reject Function

### ISSUE THREAD

**Issue by Robert-Schurig** [Robert-Schurig/Capstone-App#3]
### Value Proposition

As a user, I need to see the option to like or reject a displayed image

### Description

![Bildschirm­foto 2022-11-28 um 11 57 43](https://user-images.githubusercontent.com/114500583/204265548-657873d6-476d-4e66-8c04-b28f25a4b145.png)

### Acceptance Criteria

- [ ] Two icons are visible below the displayed image
- [ ] These icons are clickable

### Tasks

- [ ] Create new branch
- [ ] add Like and Reject Button with respective icons

### Sizing/Complexity

S
