### ISSUE TITLE
#3 Add NavBar

### ISSUE THREAD

**Issue by Robert-Schurig** [Robert-Schurig/Capstone-App#4]
### Value Proposition

As a user, I need to see a navbar with 4 icons on the bottom of the page to be able to navigate between the pages.

### Description

![Bildschirm­foto 2022-11-28 um 12 32 29](https://user-images.githubusercontent.com/114500583/204267829-76d323bd-b3be-4286-97d0-8479f866f5c5.png)

### Acceptance Criteria

- [ ] navbar is visible at the bottom of the page
- [ ] by clicking on the icon the respective page opens
- [ ] the icon of the page remains highlighted as long as the user is on the page.

### Tasks

(for developers team)

- [ ] create a new branch
- [ ] create folders and index.js-files for each page
- [ ] create a navbar component
- [ ] add icons
- [ ] add functionality to highlight the page that is displayed
- [ ] link the pages
- [ ] add the navbar to the _app.js

### Sizing/Complexity

M
