### ISSUE TITLE
#5 Optimize image display

### ISSUE THREAD

**Issue by Robert-Schurig** [Robert-Schurig/Capstone-App#8]
### Value Proposition

As a user, I want to see each picture in its original aspect ratio
to be able to see a version that comes close to the original to know whether I like it or not.

### Description

![Bildschirm­foto 2022-12-05 um 10 04 18](https://user-images.githubusercontent.com/114500583/205597212-5bee9d02-9065-4fbf-a458-479b25200540.png)

### Acceptance Criteria

- [x] the displayed images have different sizes and aspect ratios.
- [x] On the home page, these differences have to be visible to show the best quality possible of each image

### Tasks

(for developers team)

- [x] add the fill and object-fit properties to the image element 

### Sizing/Complexity

S

**Comment by marcos-de-barros-vioque** [comment]
LGTM!
