### ISSUE TITLE
#6 Save changes permanently

### ISSUE THREAD

**Issue by Robert-Schurig** [Robert-Schurig/Capstone-App#9]
### Value Proposition

As a user, I want my saved favorites to be saved when I start a new session
to be able to continue where I finished in my previous session.

### Description

![Bildschirm­foto 2022-12-05 um 12 16 11](https://user-images.githubusercontent.com/114500583/205624649-30479b6e-9c01-4465-b14b-69d19ddbc2af.png)

### Acceptance Criteria

- [ ] If the user starts the app again he still needs to se the favorites he saved in the previous session.

### Tasks

(for developers team)

- [ ] Define a key to identify the stored data in local storage
- [ ] Define a variable for the stored data.
- [ ] Add a reading and a writing method for local storage 
- [ ] Add an option for an empty local storage

### Sizing/Complexity

M

**Comment by actyvystom** [comment]
Hi Robert,
so your user story is titled local storage but your value proposition mentions saved favorites and a new session... 
I assume that you want to save the favorites to local storage as soon as they are marked as favorites, right? 
So I suggest to rename the user story to what it is really about ;) (e.g. save favorites persistently) and give more detail to the corresponding (development) tasks and acceptance criteria.

**Comment by Robert-Schurig** [comment]
I did some changes. Curious if the US meets the requirements.

**Comment by actyvystom** [comment]
I bet you can find some more entries to extend your task list ;-) a hint: what is needed to implement local storage and to put items into it?

**Comment by Robert-Schurig** [comment]
A more detailed procedure.

**Comment by actyvystom** [comment]
Nice, constantly improving 🚀 🙂
